version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    ports:
      - "9000:9000"
  scanner-ui:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: "${MINIO_ACCESS_KEY}"
      AWS_SECRET_ACCESS_KEY: "${MINIO_SECRET_KEY}"
      AWS_DEFAULT_REGION: "us-east-1"
      BUCKETNAME: "data"
      S3ENDPOINT: "--endpoint-url=http://minio:9000"
      DEBUG: "true"
      ESURL: "http://es:9200"
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - es
      - minio
  # zaproxy:
  #   image: owasp/zap2docker-weekly
  #   command: sleep 3600
