version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        user: root
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-python37-dependencies-{{ checksum "poetry.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-python37-dependencies-
    - run:
        name: install dependencies
        command: |
          sudo apt-get update
          sudo apt-get install -y awscli
          poetry install
    - save_cache:
        key: v1-python37-dependencies-{{ checksum "poetry.lock" }}
        paths:
          - /home/circleci/.cache/pypoetry/virtualenvs

    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: run tests
        command: |
          poetry run ./test.sh
    - store_artifacts:
        path: test-reports
        destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: &installcf
          name: install cf-cli
          command: |
            sudo apt-get update
            sudo apt-get install wget gnupg2 apt-transport-https
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf-cli
            cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
            cf install-plugin blue-green-deploy -r CF-Community -f
      - run:
          name: deploy to cloud.gov
          command: |
            # If we do not specify a space, then deploy to the branch that we are on.
            # This lets you have dev/staging/master branches that automatically go to the right place.
            if [ -z "$CF_SPACE" ] ; then
              export CF_SPACE="$CIRCLE_BRANCH"
            fi
            if [ -z "$CF_ORG" ] ; then
              echo CF_ORG not set, aborting
              exit 1
            fi
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"

            # generate our requirements.txt file on the fly
            poetry export -f requirements.txt > requirements.txt
            ./deploy-cloudgov.sh zdt

  scan:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          <<: *installcf
      - run:
          name: run scan
          no_output_timeout: 1h
          command: |
            # If we do not specify a space, then deploy to the branch that we are on.
            # This lets you have dev/staging/master branches that automatically go to the right place.
            if [ -z "$CF_SPACE" ] ; then
              export CF_SPACE="$CIRCLE_BRANCH"
            fi
            if [ -z "$CF_ORG" ] ; then
              echo CF_ORG not set, aborting
              exit 1
            fi
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"

            poetry install
            poetry run ./spawn_scans.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Add more branches here if you want dev/staging/whatever environments
              only:
                - master
  nightly:
    triggers:
      - schedule:
          # this should be in the middle of the night for most everybody in the US
          cron: "45 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - scan
